version: '3'

services:

  web:
    image: votify-web:1.0.0
    build:
      context: './web'
    ports:
      - '8000:80'
    volumes:
      - './web/app:/usr/share/nginx/html'
    environment:
      - "API_ENDPOINT=http://localhost:3000/api"

  api:
    image: votify-api:1.0.0
    build:
      context: './api'
      args:
        PROD: "false"
    ports:
      - '3000:3000'
    volumes:
      - './api:/app'
    depends_on:
      - db
    environment:
      - "PGUSER=postgres"
      - "PGHOST=db"
      - "PGDATABASE=votify"
      - "PGPASSWORD=password"
      - "PGPORT=5432"

  db:
    image: postgres:10-alpine
    ports:
      - '5432:5432'
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=votify"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 30s
      retries: 3
