AWSTemplateFormatVersion: 2010-09-09

Description: Votify Shared Infrastructure Configuration

Parameters:
  InstallationName:
    Type: String
    Description: Indentifier for entire stack and related resources
  VPC:
    Type: AWS::EC2::VPC::Id
    Description: VPC to deploy cluster into
  Cluster:
    Type: String
    Description: ECS Cluster to Deploy Service into
  DesiredCount:
    Type: String
    Description: Number of tasks to scale the service initially
  RepoUrl:
    Type: String
    Description: Docker Repository URL
  DockerImageAndTag:
    Type: String
    Description: The image name and tag
  LoadBalancerListener:
    Type: String
    Description: The load balancer listener (HTTP - Port 80)
  DbHost:
    Type: String
    Description: Database Host
  DbPort:
    Type: String
    Description: Database port
  DbUser:
    Type: String
    Description: Database user
  DbPass:
    Type: String
    NoEcho: true
    Description: Database password

Resources:

  CloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${InstallationName}-api
      RetentionInDays: 30

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      Role:
        Fn::ImportValue:
            !Sub ${InstallationName}-ServiceRole
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: api
          ContainerPort: 3000
          TargetGroupArn: !Ref TargetGroup

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: api-service
      ContainerDefinitions:
        - Name: api
          Essential: true
          Image: !Sub ${RepoUrl}/${DockerImageAndTag}
          Cpu: 1024
          Memory: 512
          Environment:
            - Name: PGUSER
              Value: !Ref DbUser
            - Name: PGHOST
              Value: !Ref DbHost
            - Name: PGPASSWORD
              Value: !Ref DbPass
            - Name: PGDATABASE
              Value: votify
            - Name: PGPORT
              Value: 5432
          PortMappings:
            - ContainerPort: 3000
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref CloudWatchLogsGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: api

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VPC
      Port: 3000
      Protocol: HTTP
      Matcher:
          HttpCode: 200-299
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /api/health
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref LoadBalancerListener
      Priority: 1
      Conditions:
        - Field: path-pattern
          Values:
            - '/api/*'
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
